export interface Player {
    name: string;
    library: string[];
    commanders: string[];
}

export const players: Player[] =
    [
        {
            name: `Shimmery Boi`,
            library: [
                `Lotus Petal`,
                `Mana Crypt`,
                `Nihil Spellbomb`,
                `Orzhov Signet`,
                `Sensei's Divining Top`,
                `Candelabra of Tawnos`,
                `Sol Ring`,
                `Lion's Eye Diamond`,
                `Mox Opal`,
                `Mox Diamond`,
                `Mana Vault`,
                `Chrome Mox`,
                `Talisman of Dominance`,
                `Scroll Rack`,
                `Azorius Signet`,
                `Talisman of Progress`,
                `Fellwar Stone`,
                `Grim Monolith`,
                `Helm of Awakening`,
                `Dimir Signet`,
                `Isochron Scepter`,
                `Aetherflux Reservoir`,
                `Laboratory Maniac`,
                `Shimmer Myr`,
                `Notion Thief`,
                `Jace, Vryns Prodigy`,
                `Mystic Remora`,
                `Grasp of Fate`,
                `Necropotence`,
                `High Tide`,
                `Mana Drain`,
                `Counterspell`,
                `Mystical Tutor`,
                `Vampiric Tutor`,
                `Dark Ritual`,
                `Frantic Search`,
                `Gush`,
                `Force of Will`,
                `Pact of Negation`,
                `Mental Misstep`,
                `Swan Song`,
                `Spell Pierce`,
                `Quicken`,
                `Negate`,
                `Ad Nauseam`,
                `Swords to Plowshares`,
                `Cabal Ritual`,
                `Silence`,
                `Enlightened Tutor`,
                `Hurkyl's Recall`,
                `Angel's Grace`,
                `Brainstorm`,
                `Chain of Vapor`,
                `Flusterstorm`,
                `Impulse`,
                `Delay`,
                `Dramatic Reversal`,
                `Lim-Dûl's Vault`,
                `Cyclonic Rift`,
                `Underground Sea`,
                `Polluted Delta`,
                `Ancient Tomb`,
                `Windswept Heath`,
                `Watery Grave`,
                `Verdant Catacombs`,
                `Flooded Strand`,
                `Tundra`,
                `Swamp`,
                `Scrubland`,
                `Scalding Tarn`,
                `Marsh Flats`,
                `Mana Confluence`,
                `Island`,
                `Island`,
                `Island`,
                `Island`,
                `Island`,
                `Island`,
                `Island`,
                `Island`,
                `Hallowed Fountain`,
                `Arid Mesa`,
                `Misty Rainforest`,
                `Command Tower`,
                `City of Brass`,
                `Bloodstained Mire`,
                `Godless Shrine`,
                `Gemstone Caverns`,
                `Imperial Seal`,
                `Yawgmoth's Will`,
                `Toxic Deluge`,
                `Windfall`,
                `Timetwister`,
                `Doomsday`,
                `Ponder`,
                `Gitaxian Probe`,
                `Preordain`,
                `Demonic Tutor`,
                `Merchant Scroll`
            ],
            commanders: [`Zur the Enchanter`]
        },
        {
            name: `Jhoi Rider`,
            library: [
                `Academy Ruins`,
                `Aetherflux Reservoir`,
                `Ancient Tomb`,
                `Arid Mesa`,
                `Back to Basics`,
                `Baral, Chief of Compliance`,
                `Blink of an Eye`,
                `Blood Moon`,
                `Bloodstained Mire`,
                `Brainstorm`,
                `Buried Ruin`,
                `Cascade Bluffs`,
                `Cavern of Souls`,
                `Chain of Vapor`,
                `Chrome Mox`,
                `Command Tower`,
                `Counterspell`,
                `Cursed Totem`,
                `Cyclonic Rift`,
                `Dispel`,
                `Dramatic Reversal`,
                `Etherium Sculptor`,
                `Everflowing Chalice`,
                `Fabricate`,
                `Fellwar Stone`,
                `Flooded Strand`,
                `Flusterstorm`,
                `Force of Will`,
                `Gilded Drake`,
                `Gitaxian Probe`,
                `Grafdigger's Cage`,
                `Grim Monolith`,
                `Helm of Awakening`,
                `Hurkyl's Recall`,
                `Impulse`,
                `Inventors' Fair`,
                `Isochron Scepter`,
                `Izzet Signet`,
                `Lotus Petal`,
                `Magus of the Moon`,
                `Mana Crypt`,
                `Mana Drain`,
                `Mana Vault`,
                `Mental Misstep`,
                `Merchant Scroll`,
                `Mind Stone`,
                `Misty Rainforest`,
                `Mox Diamond`,
                `Mox Opal`,
                `Muddle the Mixture`,
                `Mystic Remora`,
                `Mystical Tutor`,
                `Negate`,
                `Paradox Engine`,
                `Paradoxical Outcome`,
                `Phyrexian Revoker`,
                `Pithing Needle`,
                `Polluted Delta`,
                `Ponder`,
                `Preordain`,
                `Prismatic Lens`,
                `Pyroblast`,
                `Rebuild`,
                `Rhystic Study`,
                `Rolling Earthquake`,
                `Scalding Tarn`,
                `Sensei's Divining Top`,
                `Shivan Reef`,
                `Silent Gravestone`,
                `Snow-Covered Island`,
                `Snow-Covered Island`,
                `Snow-Covered Island`,
                `Snow-Covered Island`,
                `Snow-Covered Island`,
                `Snow-Covered Island`,
                `Snow-Covered Island`,
                `Snow-Covered Island`,
                `Snow-Covered Island`,
                `Snow-Covered Island`,
                `Snow-Covered Mountain`,
                `Sol Ring`,
                `Spell Pierce`,
                `Steam Vents`,
                `Swan Song`,
                `The Tabernacle at Pendrell Vale`,
                `Thought Vessel`,
                `Timetwister`,
                `Tormod's Crypt`,
                `Torpor Orb`,
                `Transmute Artifact`,
                `Volcanic Island`,
                `Voltaic Key`,
                `Walking Ballista`,
                `Wheel of Fortune`,
                `Whipflare`,
                `Whir of Invention`,
                `Winter Orb`,
                `Wooded Foothills`,
                `Words of Wind`
            ],
            commanders: [`Jhoira, Weatherlight Captain`]
        },
        {
            name: `Hulkster`,
            library: [
                `Chrome Mox`,
                `Lotus Petal`,
                `Mana Crypt`,
                `Mox Diamond`,
                `Sol Ring`,
                `Arbor Elf`,
                `Birds of Paradise`,
                `Bloom Tender`,
                `Dark Confidant`,
                `Deathrite Shaman`,
                `Elves of Deep Shadow`,
                `Elvish Mystic`,
                `Fyndhorn Elves`,
                `Llanowar Elves`,
                `Noble Hierarch`,
                `Priest of Titania`,
                `Notion Thief`,
                `Sacred Guide`,
                `Hapless Researcher`,
                `Spellseeker`,
                `Laboratory Maniac`,
                `Gilded Drake`,
                `Protean Hulk`,
                `Sylvan Safekeeper`,
                `Carpet of Flowers`,
                `Mystic Remora`,
                `Sylvan Library`,
                `Utopia Sprawl`,
                `Wild Growth`,
                `Training Grounds`,
                `Freed from the Real`,
                `Abrupt Decay`,
                `Ad Nauseam`,
                `Assassin's Trophy`,
                `Brainstorm`,
                `Chain of Vapor`,
                `Counterspell`,
                `Cyclonic Rift`,
                `Dark Ritual`,
                `Delay`,
                `Dispel`,
                `Flusterstorm`,
                `Force of Will`,
                `Lim-Dûl's Vault`,
                `Mana Drain`,
                `Mental Misstep`,
                `Mystical Tutor`,
                `Nature's Claim`,
                `Negate`,
                `Noxious Revival`,
                `Pact of Negation`,
                `Spell Pierce`,
                `Swan Song`,
                `Tainted Pact`,
                `Vampiric Tutor`,
                `Flash`,
                `Pongify`,
                `Summoner's Pact`,
                `Worldly Tutor`,
                `Bayou`,
                `Bloodstained Mire`,
                `Breeding Pool`,
                `City of Brass`,
                `Command Tower`,
                `Exotic Orchard`,
                `Flooded Strand`,
                `Forbidden Orchard`,
                `Forest`,
                `Gemstone Caverns`,
                `Island`,
                `Mana Confluence`,
                `Marsh Flats`,
                `Misty Rainforest`,
                `Morphic Pool`,
                `Polluted Delta`,
                `Savannah`,
                `Scalding Tarn`,
                `Tropical Island`,
                `Tundra`,
                `Underground Sea`,
                `Verdant Catacombs`,
                `Watery Grave`,
                `Windswept Heath`,
                `Wooded Foothills`,
                `Yavimaya Coast`,
                `Overgrown Tomb`,
                `Underground River`,
                `Tarnished Citadel`,
                `Demonic Tutor`,
                `Gitaxian Probe`,
                `Imperial Seal`,
                `Ponder`,
                `Preordain`,
                `Toxic Deluge`,
                `Timetwister`,
                `Windfall`,
                `Merchant Scroll`,
                `Diabolic Intent`
            ],
            commanders: [
                `Thrasios, Triton Hero`,
                `Tymna the Weaver`
            ]
        },
        {
            name: `Turns McGee`,
            library: [
                `Azorius Signet`,
                `Chalice of the Void`,
                `Sol Ring`,
                `Talisman of Progress`,
                `Cursed Totem`,
                `Fellwar Stone`,
                `Grafdigger's Cage`,
                `Lightning Greaves`,
                `Sensei's Divining Top`,
                `Chrome Mox`,
                `Mox Diamond`,
                `Mana Crypt`,
                `Scroll Rack`,
                `Baral, Chief of Compliance`,
                `Grand Arbiter Augustin IV`,
                `Jace, Vryn's Prodigy`,
                `Linvala, Keeper of Silence`,
                `Academy Rector`,
                `Aven Mindcensor`,
                `Alms Collector`,
                `Blind Obedience`,
                `Land Tax`,
                `Mystic Remora`,
                `Rhystic Study`,
                `Counterbalance`,
                `Dovescape`,
                `Anticipate`,
                `Brainstorm`,
                `Chain of Vapor`,
                `Counterspell`,
                `Cyclonic Rift`,
                `Dig Through Time`,
                `Disenchant`,
                `Enlightened Tutor`,
                `Fact or Fiction`,
                `Flusterstorm`,
                `Force of Will`,
                `High Tide`,
                `Impulse`,
                `Mana Drain`,
                `Mental Misstep`,
                `Muddle the Mixture`,
                `Mystical Tutor`,
                `Negate`,
                `Pongify`,
                `Spell Pierce`,
                `Swan Song`,
                `Swords to Plowshares`,
                `Thirst for Knowledge`,
                `Winds of Rebuke`,
                `Flash`,
                `Intuition`,
                `Mana Leak`,
                `Silence`,
                `Dispel`,
                `Adarkar Wastes`,
                `Ancient Tomb`,
                `Arid Mesa`,
                `Cavern of Souls`,
                `Command Tower`,
                `Hallowed Fountain`,
                `Island`,
                `Island`,
                `Island`,
                `Island`,
                `Island`,
                `Island`,
                `Island`,
                `Island`,
                `Island`,
                `Island`,
                `Island`,
                `Mystic Gate`,
                `Nimbus Maze`,
                `Plains`,
                `Plains`,
                `Tundra`,
                `Polluted Delta`,
                `Scalding Tarn`,
                `Forbidden Orchard`,
                `Flooded Strand`,
                `Misty Rainforest`,
                `Windswept Heath`,
                `Marsh Flats`,
                `Call to Mind`,
                `Capture of Jingzhou`,
                `Compulsive Research`,
                `Manifold Insights`,
                `Serum Visions`,
                `Temporal Manipulation`,
                `Show and Tell`,
                `Sleight of Hand`,
                `Portent`,
                `Merchant Scroll`,
                `Windfall`,
                `Ponder`,
                `Preordain`,
                `Gitaxian Probe`,
                `Timetwister`

            ],
            commanders: [`Taigam, Ojutai Master`]
        }
    ];
